/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Shanaka
 */
public class saveContactsPanel extends javax.swing.JPanel {

    /**
     * Creates new form saveContactsPanel
     */
    public saveContactsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        contNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contDesc = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Contact Number : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        contNumber.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        add(contNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 190, 40));

        jLabel3.setText("Description       :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        contName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        add(contName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 210, 30));

        jLabel4.setText("Contact Name   : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        contDesc.setColumns(20);
        contDesc.setRows(5);
        contDesc.setText("No Description");
        jScrollPane1.setViewportView(contDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea contDesc;
    protected javax.swing.JTextField contName;
    protected javax.swing.JLabel contNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
